#pragma once
const int LATEST_NNINPUT_VERSION = 1;
const int NNINPUT_CHANNELS_V1 = 903;
const int NNOUTPUT_CHANNELS_POLICY_V1 = 15;
const int NNOUTPUT_CHANNELS_VALUE_V1 = 5;
const int NNOUTPUT_CHANNELS_V1 = NNOUTPUT_CHANNELS_POLICY_V1 + NNOUTPUT_CHANNELS_VALUE_V1;